// TypeScript enums matching DB enums
export type UserRole = 'admin' | 'partner' | 'worker_internal'
export type UserStatus = 'active' | 'suspended' | 'deactivated'
export type ApprovalStatus = 'pending' | 'approved' | 'rejected'
export type SensitivityLevel = 'standard' | 'sensitive' | 'highly_sensitive'
export type RiskLevel = 'low' | 'medium' | 'high'
export type TicketStatus =
  | 'draft'
  | 'submitted'
  | 'needs_scope_review'
  | 'scope_locked'
  | 'invoiced'
  | 'paid'
  | 'queued'
  | 'assigned'
  | 'in_progress'
  | 'submitted_for_review'
  | 'revision_requested'
  | 'approved'
  | 'disputed'
  | 'completed'
  | 'resolved'
  | 'expired'
  | 'admin_closed_no_response'
  | 'cancelled'
export type TicketCategory =
  | 'data_cleanup_import_prep'
  | 'data_normalization_report_prep'
  | 'crm_import_failure_diagnosis'
export type PricingTier = 'pilot' | 'standard' | 'complex' | 'custom'
export type AssignmentStatus = 'pending' | 'acknowledged' | 'in_progress' | 'completed' | 'reassigned'
export type SubmissionStatus = 'submitted' | 'under_review' | 'approved' | 'revision_requested' | 'rejected'
export type ReviewDecision = 'approved' | 'revision_requested' | 'rejected'
export type LedgerType = 'invoice_payment' | 'worker_payout' | 'refund' | 'credit' | 'adjustment'
export type LedgerStatus = 'pending' | 'confirmed' | 'failed' | 'reversed'
export type PayoutBatchStatus = 'draft' | 'processing' | 'completed' | 'failed'
export type AttachmentRole = 'input' | 'sample' | 'deliverable' | 'issue_log' | 'mapping_doc' | 'payout_export'
export type CommentVisibility = 'partner_admin' | 'worker_admin' | 'internal_only'
export type DisputeStatus =
  | 'open'
  | 'under_review'
  | 'resolved_full_refund'
  | 'resolved_partial_refund'
  | 'resolved_no_refund'
  | 'closed'
